version: '3.8'

services:
  # The Cypress E2E testing service
  cypress-e2e:
    build:
      context: .
      dockerfile: etc/docker/cypress/Dockerfile
    networks:
      - nextapp-network
    environment:
      - CYPRESS_VIDEO=false
      - CYPRESS_SCREENSHOT_ON_RUN_FAILURE=false
      - TEST_TYPE=e2e
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $PWD/cypress:/app/cypress
      - $PWD/app:/app/app:ro
      - $PWD/public:/app/public:ro
      - $PWD/styles:/app/styles:ro
  # The Cypress components testing service
  cypress-components:
    build:
      context: .
      dockerfile: etc/docker/cypress/Dockerfile
    networks:
      - nextapp-network
    environment:
      - CYPRESS_VIDEO=false
      - CYPRESS_SCREENSHOT_ON_RUN_FAILURE=false
      - DISPLAY
      - TEST_TYPE=component
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $PWD/cypress:/app/cypress:ro
      - $PWD/app:/app/app:ro
      - $PWD/public:/app/public:ro
      - $PWD/styles:/app/styles:ro
  # Run the next JS application in dev mode
  dev:
    build:
      context: .
      dockerfile: etc/docker/node/Dockerfile
    networks:
      - nextapp-network
    user: 1000:1000
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - $PWD/node_modules:/app/node_modules
      - $PWD/.next:/app/.next
      - $PWD/app:/app/app:ro
      - $PWD/public:/app/public:ro
      - $PWD/styles:/app/styles:ro
      - $PWD/package.json:/app/package.json
      - $PWD/tsconfig.json:/app/tsconfig.json
      - $PWD/tailwind.config.js:/app/tailwind.config.js
      - $PWD/postcss.config.js:/app/postcss.config.js
      - $PWD/yarn.lock:/app/yarn.lock
  # One time setup
  setup:
    build:
      context: .
      dockerfile: etc/docker/node/Dockerfile
    user: 1000:1000
    working_dir: /app
    volumes:
      - $PWD:/app
    entrypoint: /home/node/entrypoint-setup.sh

networks:
  nextapp-network:
