name: Build Application

on:
  push:
    branches:
      - 'main'
  release:
    types: [ published ]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Using Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Building app
        run: yarn --frozen-lockfile

      - name: Components testing
        run: yarn component:headless

      - name: E2E testing
        run: yarn e2e:headless
